name: PR

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 13
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'adopt'
        java-version: 13
    - uses: subosito/flutter-action@v2.3.0
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    - run: flutter test
